version: '3.7'

services:
    front:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            - ../public/assets/front/css:/var/public/assets/front/css
        container_name: streamshow-supertv-layout
